application:
  name: oppapi
server:
  http:
    address: localhost
    port: 8080
log:
  level: DEBUG
  format: text
repsitory:
  dbname: mongo
  url: mongodb://localhost:27017
auth:
  x_api_key: R6bSXS4pfo7bnI0zIdMqiA=
bank:
  url: http://localhost:8080/bankmock/transaction
  
